siteTitle = "Kyle Gach"
blogTitle = "Of The Web"
linkPrefix = "/notUsedYet"
email = "kyle.gach@gmail.com"
twitter = "@kylegach"
github = "kylegach"

[js]
head = """
if ('classList' in document.createElement('div') && 'querySelector' in document && 'addEventListener' in window && Array.prototype.forEach) {
  document.documentElement.classList += 'js';
  var scriptSources = [
    '//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TweenLite.min.js',
    '//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/TimelineMax.min.js',
    '//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/plugins/AttrPlugin.min.js',
    '//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/plugins/CSSPlugin.min.js',
    '//cdnjs.cloudflare.com/ajax/libs/gsap/1.18.0/easing/EasePack.min.js',
    '/bundle.js'
  ];
  for ( var i=0; i<scriptSources.length; i++ ) {
    var script = document.createElement('script');
    script.src = scriptSources[i];
    document.getElementsByTagName('body')[0].appendChild(script);
  }
}
"""
analytics = """
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-76450703-1', 'auto');
ga('send', 'pageview');
"""

favicons = """
<link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"/apple-touch-icon-57x57.png\">
<link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"/apple-touch-icon-60x60.png\">
<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"/apple-touch-icon-72x72.png\">
<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"/apple-touch-icon-76x76.png\">
<link rel=\"apple-touch-icon\" sizes=\"114x114\" href=\"/apple-touch-icon-114x114.png\">
<link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"/apple-touch-icon-120x120.png\">
<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"/apple-touch-icon-144x144.png\">
<link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"/apple-touch-icon-152x152.png\">
<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"/apple-touch-icon-180x180.png\">
<link rel=\"icon\" type=\"image/png\" href=\"/favicon-32x32.png\" sizes=\"32x32\">
<link rel=\"icon\" type=\"image/png\" href=\"/android-chrome-192x192.png\" sizes=\"192x192\">
<link rel=\"icon\" type=\"image/png\" href=\"/favicon-96x96.png\" sizes=\"96x96\">
<link rel=\"icon\" type=\"image/png\" href=\"/favicon-16x16.png\" sizes=\"16x16\">
<link rel=\"manifest\" href=\"/manifest.json\">
<link rel=\"mask-icon\" href=\"/safari-pinned-tab.svg\" color=\"#1d3653\">
<meta name=\"apple-mobile-web-app-title\" content=\"kylegach.com\">
<meta name=\"application-name\" content=\"kylegach.com\">
<meta name=\"msapplication-TileColor\" content=\"#603cba\">
<meta name=\"msapplication-TileImage\" content=\"/mstile-144x144.png\">
<meta name=\"theme-color\" content=\"#1d3653\">
"""

[header]
text = """
<p><span class=\"bold\">Hi.</span> I’m a front-end developer.</p>
<p>I use pen \u0026 paper, vectors, pixels, HTML, CSS, and JavaScript to think about and build systems on the web that help people.</p>
"""

[work]
title = "Work"
blurb = "Here are some of the more interesting projects I’ve worked on. I’ve mostly done front-end development \u0026 architecture, prototyping, and UX research \u0026 design."
dir = "work"

[writing]
title = "Writing"
blurb = "I believe design is made with words, not just pixels and code. This is where I practice."
dir = "writing"

[about]
title = "About"
text = '''
<div class="left@md mb-3 flex@sm items-center">
  <img src="/avatar.png" alt="Profile picture of Kyle" class="block w-25 flexItem-25 mx-auto mb-3 mr-3@sm ml-0@sm mb-0@sm circle border borderColor-light" />
  <p class="flexItem-auto">I care about an open, accessible, fast, responsive, and well-built web that puts people first. When I’m not working toward that, I’m probably reading, riding my bike, or enjoying a craft beer or cocktail.</p>
</div>
<div class="left@sm w-50@sm pr-2@sm mb-3 mb-0@sm">
  <h3 class="h4 mb-0">I’m Very Good With</h3>
  <ul style="margin-top:1.5rem">
    <li>HTML</li>
    <li>CSS</li>
    <li>JavaScript</li>
    <li>Progressive Enhancement</li>
    <li>Responsive Web Design</li>
    <li>Communication</li>
    <li>Learning</li>
  </ul>
</div>
<div class="left@sm w-50@sm pl-2@sm">
  <h3 class="h4 mb-0">I’m Getting Better With</h3>
  <ul style="margin-top:1.5rem">
    <li><abbr title="Accessibility">A11y</abbr></li>
    <li>Performance</li>
    <li>Build Tools (Gulp, Webpack)</li>
    <li>Typography</li>
    <li>Color Theory</li>
    <li>React</li>
  </ul>
</div>
'''
